spring.application.name=CapStoneProject
spring.output.ansi.enabled=ALWAYS
spring.jwt.secret=${JWT_SECRET}
spring.profiles.active= dev
#5 mins temp 2h
spring.jwt.accessTokenExpiration=7200000
#7 days
spring.jwt.refreshTokenExpiration=604800000